SELECT COUNT(*) AS COUNT FROM ECOLI_DATA
WHERE CONVERT(CONV(ECOLI_DATA.GENOTYPE, 10,2), CHAR) IN("1","01")
OR CONVERT(CONV(ECOLI_DATA.GENOTYPE, 10,2), CHAR) LIKE "%10_"
OR CONVERT(CONV(ECOLI_DATA.GENOTYPE, 10,2), CHAR) LIKE "%01"
;